# Generated by Django 4.1.6 on 2023-02-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('symbol_type', models.CharField(max_length=10)),
                ('decimal', models.IntegerField()),
                ('ask', models.CharField(max_length=20)),
                ('bid', models.CharField(max_length=20)),
                ('open', models.CharField(max_length=20)),
                ('high', models.CharField(max_length=20)),
                ('low', models.CharField(max_length=20)),
                ('close', models.CharField(max_length=20)),
                ('spread', models.CharField(max_length=20)),
                ('change', models.CharField(max_length=20)),
                ('change_per', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('volume', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'currency_lists',
            },
        ),
    ]
