# Generated by Django 4.1.6 on 2023-03-23 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=16)),
                ('symbol', models.CharField(max_length=10)),
                ('symbol_type', models.CharField(max_length=10)),
                ('order_type', models.CharField(max_length=10)),
                ('order_status', models.CharField(default='active', max_length=20)),
                ('order_size', models.FloatField()),
                ('open_price', models.FloatField()),
                ('open_time', models.DateTimeField(auto_now_add=True)),
                ('close_price', models.FloatField()),
                ('close_time', models.DateTimeField(null=True)),
                ('stop_loss', models.FloatField()),
                ('take_profit', models.FloatField()),
                ('profit', models.FloatField()),
                ('swap', models.FloatField()),
                ('commission', models.FloatField()),
                ('required_margin', models.FloatField()),
                ('pip_value', models.FloatField()),
                ('pip_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_trades',
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=22)),
                ('country', models.CharField(max_length=3)),
                ('account_type', models.CharField(max_length=50)),
                ('referral_code', models.CharField(max_length=50)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('verification_code', models.CharField(default='', max_length=36)),
                ('trading_account_allowed', models.IntegerField(default=1)),
                ('last_modified_by', models.CharField(default='none', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_info',
            },
        ),
    ]
