# Generated by Django 4.1.6 on 2023-04-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_usertrades_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='account_type',
        ),
    ]
