# Generated by Django 4.1.6 on 2023-06-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_useractivesymbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivesymbol',
            name='chart_interval',
            field=models.CharField(default='5m', max_length=10),
        ),
    ]
