# Generated by Django 4.1.6 on 2023-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_useractivesymbol_chart_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivesymbol',
            name='symbol_type',
            field=models.CharField(default='forex', max_length=10),
        ),
    ]
