# Generated by Django 4.1.6 on 2023-07-23 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0007_useractivesymbol_symbol_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='tradingAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=28)),
                ('server', models.CharField(max_length=20)),
                ('levrage', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0.0)),
                ('status', models.CharField(default='disabled', max_length=20)),
                ('state', models.CharField(default='trading_disabled', max_length=20)),
                ('account_type', models.CharField(default='MICRO', max_length=30)),
                ('equity', models.FloatField(default=0.0)),
                ('free_meargin', models.CharField(default=0.0, max_length=60)),
                ('loss_profit', models.FloatField(default=0.0)),
                ('account_credits', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trading_accounts',
            },
        ),
    ]
