# Generated by Django 4.1.6 on 2023-07-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_tradingaccounts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradingaccounts',
            old_name='levrage',
            new_name='leverage',
        ),
    ]
