# Generated by Django 4.1.6 on 2023-08-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_rename_levrage_tradingaccounts_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencylists',
            name='symbolShort',
            field=models.CharField(default='', max_length=10),
        ),
    ]
